# rename this file as *config.yaml*
# WARNING:
## DO NOT commit *config.yaml* file

settings:
    # [bool] Enable logging to a file
    enable_logs_to_file: false

    # [string] Radio url
    radio_url: "https://example.com/playlist.m3u8"

